export enum Icon {
  THEATER_MASKS = "theater-masks",
  ROBOT = "robot",
  DRAGON = "dragon",
  LEAF = "leaf",
  PAW = "paw",
  GAMEPAD = "gamepad",
  RUNNING = "running",
  YIN_YANG = "yin-yang",
  UTENSILS = "utensils",
  GLOBE_EUROPE = "globe-europe",
  PALETTE = "palette",
  MONUMENT = "monument",
  PRAYING_HANDS = "praying-hands",
  USER_FRIENDS = "user-friends",
  BRAIN = "brain",
  COGS = "cogs",
  LAPTOP_CODE = "laptop-code",
  CHART_LINE = "chart-line",
  GRADUATION_CAP = "graduation-cap",
}
